project: 
  type: website
  output-dir: docs
 
website: 
  title: "OHI Gulf of California: Information Hub"
  favicon: images/ohi-fav-dark.png
  site-url: "https://ohi-goc.github.io/OHI_GOC/"
  repo-url: https://github.com/ohi-goc/OHI_GOC
  repo-actions: [edit, issue]
  page-navigation: true

  page-footer:
    left: "An Ocean Health Index collaboration"
    right: "Source repository: [GitHub](https://github.com/OHI-GOC)"

  sidebar:
    logo: chapters/figs/gulf-of-california-map.jpg
    pinned: true
    align: center
    style: docked
    search: false
    collapse-level: 1
    contents:
      - href: index.qmd
        text: "🏠 Home"
      - href: chapters/overall_update.qmd
        text: "Overall Update"
      - href: chapters/OHIregions.qmd
        text: "🌎️ Map of OHI Regions"

format:
  html:
    html-math-method: katex
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    includes:
      in-header:
        - assets/css/all.css
