project: 
  type: website
  output-dir: docs
  
website: 
  page-navigation: true
  title: "OHI: Gulf of California" 
  site-url: "https://ohi-goc.github.io/OHI_GOC/" 
  repo-url: https://github.com/ohi-goc/OHI_GOC 
  repo-actions: [edit, issue]
  
  page-footer:
    right: "Source repository: https://github.com/OHI-GOC"
    left: "An Ocean Health Index collaboration"
    
  sidebar:
    logo: "chapters/figs/gulf-of-california-map.jpg"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - href: chapters/OHI.qmd
        text: "Starting an OHI assessment"
      - href: chapters/region.qmd
        text: "Identify regions"
      - href: chapters/goals.qmd
        text: "Identify goals"  
      - section: "Data"
        contents:
          - href: chapters/data/protected.qmd
            text: "Protected regions"
          - href: chapters/data/sst.qmd
            text: "Sea surface temperature"
          - href: chapters/data/fishery_production.qmd
            text: "Fishery production"
          - href: chapters/data/fishery_effort.qmd
            text: "Fishing effort"
          - href: chapters/data/habitats.qmd
            text: "Habitats"
      - href: chapters/pressures.qmd
        text: "Pressures"
      - href: chapters/resilience.qmd
        text: "Resilience"
format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    includes:
      in-header:
        - assets/css/all.css    
filters:
  - quarto


