project: 
  type: website
  output-dir: docs
 
website: 
  title: "OHI Gulf of California: Information Hub"
  site-url: "https://ohi-goc.github.io/OHI_GOC/"
  repo-url: https://github.com/ohi-goc/OHI_GOC
  repo-actions: [edit, issue]
  page-navigation: true

  page-footer:
    left: "An Ocean Health Index collaboration"
    right: "Source repository: [GitHub](https://github.com/OHI-GOC)"

  sidebar:
    logo: chapters/figs/gulf-of-california-map.jpg
    pinned: true
    align: center
    style: docked
    search: false
    collapse-level: 1
    contents:
      - href: index.qmd
        text: "🏠 Home"
      - href: chapters/OHIregions.qmd
        text: OHI regions
      - href: chapters/ao.qmd
        text: Artisanal opportunities
      - href: chapters/bd.qmd
        text: Biodiversity
      - href: chapters/cp.qmd
        text: Coastal protection
      - href: chapters/cs.qmd
        text: Carbon storage
      - href: chapters/cw.qmd
        text: Clean waters
      - href: chapters/fp.qmd
        text: Food provisioning
      - href: chapters/le.qmd
        text: Livelihoods and economies
      - href: chapters/np.qmd
        text: Natural products
      - href: chapters/sp.qmd
        text: Sense of place
      - href: chapters/tr.qmd
        text: Tourism and recreation
      - href: chapters/ss.qmd
        text: Safety and security
      - href: chapters/ol.qmd
        text: Research and ocean literacy

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    includes:
      in-header:
        - assets/css/all.css
