---
title: "Recursos del Grupo de Trabajo de Expertos"
format: html
---

<div class="button-container">
  <a href="https://ohi-goc.github.io/OHI_GOC/chapters/ewg.html" class="custom-button">
    <i class="fas fa-globe"></i> English Translation
  </a>
</div>

## ¡Bienvenidas y bienvenidos a la segunda reunión del EWG, del 20 al 22 de enero!

:::{.callout-tip} 
# Enlaces clave

La **agenda** de la reunión se encuentra [aquí.](https://docs.google.com/spreadsheets/d/1uj-wX8ZjulRe0ANkBcWkJ8pL33bdGw93cx5yUpLHH_4/edit?gid=0#gid=0) 

*Notas de la reunión:*

* [Día 1](https://docs.google.com/document/d/1XH1nKQz5E2xV3TkC-iQ6JWa8JAot_iyLqJBnZDwm0Mk/edit?tab=t.0#heading=h.kwsyc5wl8bzd)
* [Día 2](https://docs.google.com/document/d/1vK-pKE0W5vBnucxgk3HD5ZHsDwee3TJi0qqJQwkJidE/edit?tab=t.0)
* [Día 3](https://docs.google.com/document/d/1tN-Q0JTUXuplgT3OydbuzJGxjSDmI-Z0oh3FXk7SXZo/edit?tab=t.0#heading=h.kwsyc5wl8bzd)

:::

| Meta OHI | Enlace a las presentaciones | Materiales adicionales
|----------|-----------------------------|------------------------
| Provisión de Alimentos (FP) | [Haz clic aquí](https://docs.google.com/presentation/d/1CYpFMOLGcqjNDC_11URTJ0xFxqUhvLCn4oXLiKRerjs/edit?usp=drive_link) | • [Resúmenes de las reuniones](https://docs.google.com/document/d/1l4zVOSt-twGsw9FvBCq1bPtPyuienjRKovf8zbaizvE/edit?usp=drive_link)<br>• [Revisión de biomasa y CPUE](https://drive.google.com/drive/folders/1CYFI5nStx0U1xBCuOpabfZdIzj9HBsui?usp=drive_link)<br>• [Clave de especies de CONAPESCA](https://docs.google.com/spreadsheets/d/1R4klvvLAtgRxpRU9cWrVhk-Dw3672DYQw_ZfWIUqBHg/edit?usp=drive_link)<br>• [Revisión de salidas del modelo CMSY](https://drive.google.com/drive/folders/1TZZi8oVDVG3sCdagVttTtkQbFXO8Yka6?usp=drive_link)<br>• [Priorización y registro CMSY](https://docs.google.com/spreadsheets/d/1QGmvgrtZwWKkIOvi36wPm9jZuaqn-uxiNetp08Feqss/edit?gid=0#gid=0)<br>• [Registro MAR](https://docs.google.com/spreadsheets/d/1j6DH4qK-XtXD0AH6SDCzO-O5N2Dqz1GRQxDWNWHfJuQ/edit?usp=drive_link) |
| Turismo y Recreación (TR) | [Haz clic aquí](https://docs.google.com/presentation/d/1LVK5QcvnQ8TU-z3jx_GX_3cKrWBjTQASMj6AtgPQ0mo/edit?usp=drive_link) | [Gráficos interactivos](tr_extra_materials.html)
| Biodiversidad (BD) | [Haz clic aquí](https://docs.google.com/presentation/d/15ksHpfWq9duDIg7FOAP40VHnjy5R3_AsE-nrTzuNX3g/edit?usp=drive_link) | • [Resúmenes de las reuniones](https://docs.google.com/document/d/1IFH2GoHWF_8XMBelkLNQp0xbIPvyZNyFzFERgjGNWrU/edit?usp=drive_link)<br>• [Informe de Wilder et al. (2025)](https://drive.google.com/file/d/1lEzMoT_9q_Z0Mq6GZc3U7sZYToexWxvE/view?usp=drive_link)<br>• [Datos de Wilder et al. (2025)](https://docs.google.com/spreadsheets/d/1vupByXFRAW9xgoDv3TjWWZnSgQVaCE7j/edit?usp=drive_link&ouid=101513442493251196406&rtpof=true&sd=true)<br>• [Tabla de BD y notas de grupo](https://docs.google.com/spreadsheets/d/1hTDvpYjQtoSfuVSYVaiTXSFr3uTeZPCkZy3k7sofM90/edit?usp=drive_link) |
| Servicios de Hábitat | [Haz clic aquí](https://docs.google.com/presentation/d/15ksHpfWq9duDIg7FOAP40VHnjy5R3_AsE-nrTzuNX3g/edit?slide=id.g3b6b3ca3bd0_0_1102#slide=id.g3b6b3ca3bd0_0_1102) |
| Oportunidades de Acceso | [Haz clic aquí](https://docs.google.com/presentation/d/1TBDP0niiypVexpoEh0l2Pt4JfJULwPNm70a07DpB5gc/edit?usp=drive_link) | • [Resúmenes de las reuniones](https://docs.google.com/document/d/1XjBi0qHSjbso1bPnc48mBbsjcm08wJig0kZueTe4PMQ/edit?usp=drive_link)<br>• [Actividad de grupo](https://docs.google.com/spreadsheets/d/1KHIxVFt5x4G6uL5ILNCnO-QmhDUMpC_ZGmtTkRLxjBw/edit) |
| Sentido de Lugar | [Haz clic aquí](https://docs.google.com/presentation/d/1fl4kmrNkpUrtNKhbvjzmaEB82R6bK4f30vTCpfro2uk/edit?usp=drive_link) | [Materiales adicionales](chapters/tr_extra_materials.html)
| Productos Naturales | [Haz clic aquí](https://docs.google.com/presentation/d/1wLfI5LymlJHFyAxy2EE9UlRhSFDg_mJEQnrIGEEkZWg/edit?usp=drive_link) | • [Resúmenes de las reuniones](https://docs.google.com/document/d/11LrbOWL7UnQ2SU3u-POucAdKruhMNsFJ6rCkEMtNIqI/edit?usp=drive_link)<br>• [Revisión del EWG sobre Productos Naturales](https://docs.google.com/spreadsheets/d/1fdkcdXsZWKJtAijMSQyWixEjfJNzF-Elu82qAGvZWeA/edit?gid=2057563193#gid=2057563193) |
| Aguas Limpias | [Haz clic aquí](https://docs.google.com/presentation/d/1tZ-NOY5zUlKm5tYjbQq0U7wtUlUjkhWE3CjQVTrgqDQ/edit?usp=drive_link) | [Materiales adicionales](chapters/tr_extra_materials.html)
| Medios de Vida y Economías | [Haz clic aquí](https://docs.google.com/presentation/d/1eeBdWPzIhgnPMRyTr_c28q4iO204dq6w27MWfwBVuEY/edit?usp=drive_link) | [Materiales adicionales](chapters/tr_extra_materials.html)
| Seguridad y Protección | [Haz clic aquí](https://docs.google.com/presentation/d/1u7sp7RX9laoUO1-HdwB-fEculSI5nDnQ6XySn0WbrIk/edit?usp=drive_link) | [Materiales adicionales](chapters/tr_extra_materials.html)
| Presiones / Tendencias / Resiliencia | [Haz clic aquí](https://docs.google.com/presentation/d/1beZx6xqcT4kq024AyqIaxOqdcL6Chvwf36rSOh08m5U/edit?usp=drive_link) |
---

