---
title: " "
format: html
toc: true
---

## Sea surface temperature for the Gulf of California

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
# refer to ohi_goc_prep/_pressures/prs_sst/v2025/sst_layer_prep.qmd for full data prep
library(here)
library(tidyverse)

# ---- sources! ----
# source(here("workflow", "R", "common.R")) # file creates objects to process data
## set the mazu and neptune data_edit share based on operating system
dir_M             <- c('Windows' = '//mazu.nceas.ucsb.edu/ohi',
                       'Darwin'  = '/Volumes/ohi',    ### connect (cmd-K) to smb://mazu/ohi
                       'Linux'   = '/home/shares/ohi')[[ Sys.info()[['sysname']] ]]

# ---- set year and file path info ----
current_year <- 2025 # Update this in the future!!
version_year <- paste0("v",current_year)
data_dir_version_year <- paste0("d", current_year)
```

Sea surface temperature (SST) is a critical indicator of ocean health, influencing marine ecosystems, biodiversity, and climate patterns. Changes in SST can affect species distributions, disrupt food webs, and contribute to coral bleaching events. By analyzing historical SST data (1980–2000) alongside recent trends (2014–2023), we can identify long-term patterns, assess the impacts of climate change, and inform strategies for sustainable ocean management.

The interactive tool below lets you explore how sea surface temperatures have changed in the Gulf of California by comparing historical patterns (1980-2000) with recent conditions (2014-2023). This visualization helps identify areas that may need special attention for conservation and management efforts.  As we progress, the data will be used to shape future goals and pressures.


<iframe src="https://qcz3wo-sophia-lecuona.shinyapps.io/sst_yearly_comparison_shiny_app/" width="100%" height="600"></iframe>



